### ISSUE TITLE
Can read Wiki but not add to it 

### ISSUE THREAD

**Issue by RoxanneA-alt** [CodeForPhilly/pa-wildflower-selector#2]
Hey, Tom. How can I edit the Wiki?  I can read it but not edit.  Is there a trick to that or do I need certain access?  I want to add this Notion workspace to the wiki https://www.notion.so/170332ca05414a31802d360f04614340?v=4348fdfe04924f80b3e97c34089bd63a

**Comment by CristinaZanoni** [comment]
Same here, I want to add the Data Analysis Report https://docs.google.com/document/d/1iJnHXFsBfNXmvNk95NHQikaNeze8XezKYArCziRfMOk/edit?usp=sharing
