### ISSUE TITLE
How do we push updates to the deployed site (with Helm)?

### ISSUE THREAD

**Issue by boutell** [CodeForPhilly/pa-wildflower-selector#34]
Talk to Chris Alfano

**Comment by ZacharyLeahan** [comment]
Hey Tom - I'll pick this up.

**Comment by boutell** [comment]
Sounds good Zach. Things we need:

* MongoDB (usually a separate container accessible to the app container), with a persistent volume so it doesn't lose its contents on future deployments
* In the app container:
  * Node.js 16.x
  * Imagemagick
  * Persistent volume for /images, so we don't have to redownload all the images on every deployment

Originally the plan was for me to come up with a docker-compose file, which I'm more familiar with than Helm, but we could skip that step.
