### ISSUE TITLE
Readme setup says cd ui npm install but there is no ui folder.

### ISSUE THREAD

**Issue by ZacharyLeahan** [CodeForPhilly/pa-wildflower-selector#43]
Do we need the "cd ui
npm install"
step?

There is no ui folder.
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/23/2022  10:45 AM                deployment
d-----         1/23/2022  10:45 AM                lib
d-----         1/23/2022  10:52 AM                node_modules
d-----         1/23/2022  10:45 AM                original-assets
d-----         1/23/2022  10:45 AM                public
d-----         1/23/2022  10:45 AM                scripts
d-----         1/23/2022  10:45 AM                src
-a----         1/23/2022  10:45 AM            174 .gitignore
-a----         1/23/2022  10:45 AM            172 app.js
-a----         1/23/2022  10:45 AM             78 babel.config.js
-a----         1/23/2022  10:45 AM           9798 download.js
-a----         1/23/2022  10:45 AM          35819 LICENSE
-a----         1/23/2022  10:45 AM           8096 massage.js
-a----         1/23/2022  10:52 AM         511775 package-lock.json
-a----         1/23/2022  10:45 AM           1987 package.json
-a----         1/23/2022  10:45 AM           2045 README.md
-a----         1/23/2022  10:45 AM           1069 vue.config.js

**Comment by boutell** [comment]
This step no longer exists, I merged the folders. I've updated the README. Good catch.
