### ISSUE TITLE
Treatment for large numbers of chips on desktop

### ISSUE THREAD

**Issue by boutell** [CodeForPhilly/pa-wildflower-selector#49]
On mobile they scroll horizontally.

On desktop, I have them scrolling horizontally at the moment, but that's just a guess because I don't have enough data from looking at the designs (I absolutely could be missing previous direction here, sorry).

It currently looks rough on Windows where scrollbars are more visually prominent, and it's somewhat unusual to do horizontal scrolling on desktop, so I wanted to ask if I should ditch the horizontal scrolling on desktop only and just have the chips tile to a second row.

You can see this pretty easily by selecting a lot of filters on the site on desktop at https://pa-wildflower-selector.boutell.dev/

**Comment by CristinaZanoni** [comment]
You are right! you can "ditch the horizontal scrolling on desktop only and just have the chips tile to a second row."
