### ISSUE TITLE
"Showy" should use the icon Cristina provided in the figma file

### ISSUE THREAD

**Issue by boutell** [CodeForPhilly/pa-wildflower-selector#55]
* "Showy" became a necessary filter when I implemented the new quick search, which relies on it to implement "do you want flowers." It pretty much means "blooming." All data used to implement quick search must be equivalent to some combo of filters as well.
* "Flowering Months" needs an icon to show on its chip when active.

**Comment by CristinaZanoni** [comment]
<img width="421" alt="Screen Shot 2022-02-23 at 10 52 02" src="https://user-images.githubusercontent.com/84871802/155356086-c39c2498-ac84-4dad-95bc-28100be51d42.png">

How does this look? The icon is the Figma file > Style Guides > Icons and here https://www.svgrepo.com/svg/53672/month-calendar

**Comment by CristinaZanoni** [comment]
![leaf-svgrepo-com](https://user-images.githubusercontent.com/84871802/155366191-311cc0ba-ca57-4284-ae17-2b7db163e242.svg)
We already have an info tip for this one. The icon is the Figma file > Style Guides > Icons
