### ISSUE TITLE
UX: End of mobile quiz does not show plants

### ISSUE THREAD

**Issue by ZacharyLeahan** [CodeForPhilly/pa-wildflower-selector#64]
UX Question: On mobile, at the end of the quiz, the user is taken back to the filter screen and not shown plants.  They need to click "apply" to continue.  Should the user be taken right to the plants?

**Comment by CristinaZanoni** [comment]
Yes, the user should be taken right to the plants. After clicking "show plants" on mobile the user goes to the list of plants with filters already applied.
