### ISSUE TITLE
Results from my searching for missing images from crawler 

### ISSUE THREAD

**Issue by RoxanneA-alt** [CodeForPhilly/pa-wildflower-selector#8]
I went through 12 [results with missing images](https://docs.google.com/spreadsheets/d/1A8NGzjm1rm_QXBY3hJicYVK13GiYf-qKrgC71q1l0pQ/edit#gid=0) .  Majority are readily available in wikimedia.  Only two Amelanchier ×intermedia and Amelanchier ×neglecta were somewhat difficult to find, because they are nothospecies.  ( i put this in the notes section in the database btw) which is a hybrid of two other species.  I suspect the small "x" in the name is designating this? for when I remove the small "x: I find the notho species.  The remaining 10 however, as mentioned are readily found in wikimedia.  

Can the crawler be adjusted to find those readily available in wikimedia? Thanks

**Comment by boutell** [comment]
This was resolved with a new import.
